resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/brainsik/json-store-ci-demo.git
      branch: master

  - name: version
    type: semver
    source:
      driver: git
      initial_version: 2.2.0
      uri: git@github.com:brainsik/json-store-ci-demo.git
      branch: concourse-semver
      file: version
      private_key: {{github-private-key}}

  - name: package
    type: s3
    source:
      region_name: us-west-2
      bucket: truss-brainsik-json-store-ci-demo
      regexp: json-store-(.*).tar.gz
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
      server_side_encryption: AES256
      private: true

  - name: release
    type: github-release
    source:
      user: brainsik
      repository: json-store-ci-demo
      access_token: {{github-personal-access-token}}

jobs:
  - name: build-package
    plan:
    - get: source-code
      trigger: true
    - get: version
      params:
        bump: patch
    - task: build-source-package
      file: source-code/ci/build-source-package.yml
    - put: package
      params:
        file: source-package/*
    - put: version
      params: {file: version/version}

  - name: test-package
    plan:
    - get: source-code
    - get: package
      passed:
        - build-package
      trigger: true
    - task: run-package-tests
      file: source-code/ci/run-package-tests.yml

  - name: release-it
    plan:
    - get: source-code
    - get: package
      passed:
        - test-package
    - task: create-release
      file: source-code/ci/create-release.yml
    - put: release
      params:
        name: path/to/name/file
        tag: path/to/tag/file
        body: path/to/body/file
        globs:
        - paths/to/files/to/upload-*.tgz
